remote_theme: just-the-docs/just-the-docs
title: DW E-Scooter Pipeline
description: Project from Susanna Amy Huang, Mi-Jou Hsiao, Christina M√ºller and Victoria-Kim Bui for the module BIPM-M01-F01-WiSe-2025-53707

mermaid:
  version: "9.4.3"

callouts:
  tip:
    title: ü§ç Tip
    color: purple
  info:
    title: ‚ÑπÔ∏è Info
    color: blue
  attention:
    title: ‚ùï Attention
    color: yellow

# aktiviert die automatische Sidebar mit frontmatter
nav_order: 1
