remote_theme: just-the-docs/just-the-docs
title: DW E-Scooter Pipeline
description: Project from Susanna Amy Huang, Mi-Jou Hsiao, Christina M√ºller and Victoria-Kim Bui for the module BIPM-M01-F01-WiSe-2025-53707
mermaid:
  version: "9.4.3" # Pick version from https://cdn.jsdelivr.net/npm/mermaid/
callouts:
  tip:
    title: ü§ç Tip
    color: purple
  info:
    title: ‚ÑπÔ∏è Info
    color: blue
  attention:
    title: ‚ùï Attention
    color: yellow
sidebar:
  - title: Project Structure
    url: /docs/project_structure/
  - title: Data Schema
    url: /docs/data-schema/
  - title: Data Model
    url: /docs/data-model/
  - title: Design Desicions
    url: /docs/design-desicions/
  - title: Goals Archieved & Missed
    url: /docs/goals-archieved-missed/
  - title: Possibile Improvements
    url: /docs/possibile-improvements/
  - title: Contributions
    url: /docs/contributions/

